# Komut satırı SQLite Giriş {#sec-command-line-sqlite-intro}


## SQLite

- Ubuntu gibi bir çok linux kurulumunda yüklü olarak gelir.

- Macintosh'ta eski bir sürümü vardır.
Güncellenmesi tavsiye edilir.
brew kullanılarak kurulması tavsiye edilir.
Ama eğer istenirse, aşağıdaki siteden yüklenebilir.


```bash
brew install sqlite
```

- Windows'ta scoop kullanılarak kurulması tavsiye edilir. 

```bash
scoop install sqlite
```

Ama eğer istenirse, aşağıdaki siteden yüklenebilir.
[sqlite3](https://www.sqlite.org/cli.html)


## SQLite Komut satırı Demo

| Sıra | Komut                                                |
|------|------------------------------------------------------|
| 01   | [Chinook veritabanı github'tan indir](https://github.com/ati-ozgur/course-database/raw/refs/heads/main/databases/chinook.sqlite)                  |
| 02   | Chinook veri tabanı aç: sqlite3 chinook.sqlite       |
| 03   | .help ile komut listesini göster                     |
| 04   | .tables ile tabloları göster                         |
| 05   | Tablolardan SELECT ile bilgi almayı göster           |
| 06   | .headers on ile kolon isimlerin göster veya gösterme |
| 07   | .mode ile SELECT çıktısını farklılaştırmayı göster   |
| 08   | .output ile dosya ortamına SELECT ile aktarım yap    |
| 09   | .schema ile tablo oluşturma betiklerin göster        |
| 10   | .dump ile veri tabanı tam kopyalamayı göster         |
| 11   | .read ile SQL komutu çalıştırmayı göster.            |
| 12   | .exit ile komut satırında çıkma                      |