# Birincil Anahtar - Primary Key

İlişkisel veri tabanların birincil anahtarlar tablo üzerindeki kayıtları biricik olarak belirlerler. 
Bir kayıtı biricik olarak bulmanın yararı, bu kayıtı sorgulamanın ve güncellemenin bu anahtar ile çok daha hızlı bir şekilde yapılmasıdır. 
Aynı şekilde tablolar arasındaki ilişkiler birincil anahtarlara bağlanan yabancı anahtarlar ile sağlanır. 

Örneğin KISI ve KISI_EGITIM tablolarımız olduğunu varsayalım. Bir kişinin hangi eğitimleri aldığını KISI_EGITIM tablosunda Kisi birincil anahtarı kullanılarak yapılır. 

Bundan dolayı veritabanı tasarımında birincil anahtar seçimi çok önemlidir.

Birincil anahtar seçiminde 2 farklı düşünce vardır. 
Bunlar Doğal Anahtar ve Sentetik Anahtardır.

İkisi arasındaki farklar, artıları ve eksileri anlatmadan önce benim sentetik anahtar taraftarı olduğumu belirteyim.




{{< include ../course-contents/database-design-primary-key-natural-key-tr.qmd >}}
{{< include ../course-contents/database-design-primary-key-synthetic-key-tr.qmd >}}


{{< include ../course-contents/database-design-primary-key-auto-number-identity-tr.qmd >}}



{{< include ../course-contents/database-design-primary-key-sequences-tr.qmd >}}
 






