## Third Normal Form

Third normal form is about extra information in the columns.
When a non key column contains information about another non key column, 3rd normal form is violated.

Consider following example:


| Employee      | Department  | Building      |
|---------------|-------------|---------------|
| John Doe      | Sales       | Main Building |
| Jane Smith    | Marketing   | Main Building |
| David Lee     | Engineering | Building Eng  |
| Atilla Özgür  | Engineering | Building Eng  |
| Sarah Jones   | Finance     | Main Building |
| Michael Brown | HR          | Main Building |


If each department is located in single building, then the building column is about the department not about the employee.
This design has following problems:

- The building column is repeated for every department
- If the building changes for a department, lets say company decided to move marketing to a new building, every marketing employee row has to be changed.
- due to redundant information, data update, insert anomalies may occur. For the same department, different rows may show different building information.
- if a department has no employees (i.e. a newly established one), how to store  building information of this department?

To convert this table to the 3rd normal form:

1. First and second normal forms has to be satisfied
2. divide this extra information to its own table. 
See following tables

| Employee      | Department  |
|---------------|-------------|
| John Doe      | Sales       |
| Jane Smith    | Marketing   |
| David Lee     | Engineering |
| Atilla Özgür  | Engineering |
| Sarah Jones   | Finance     |
| Michael Brown | HR          |


| Department  | Building      |
|-------------|---------------|
| Sales       | Main Building |
| Marketing   | Main Building |
| Engineering | Building Eng  |
| Engineering | Building Eng  |
| Finance     | Main Building |
| HR          | Main Building |


