## Natural Key

Natural Key proponents recommend choosing a primary key based on information that already exists in the domain when designing a database. 
Since users are already familiar with this information, natural keys will be much easier to use and adopt. 
These keys are also easier to use by people who are not familiar with database logic. 


In table @tbl-table-primary-key-natural-key-example-city-table, license plateCode is selected as the primary key.


|   CITY    |    |
|:---------:|:--:|
| PlateCode | PK |
|  CityName |    |

: Natural Key Example 1 - City Table {#tbl-table-primary-key-natural-key-example-city-table}


The advantage of Natural Keys is that they are already known as I mentioned before. 
As a disadvantage, since these keys have meaning in the domain, our database schema has become domain dependent.
Keys need to be changed in requirement changes. 
For example, let's assume that TcIdentityNo is selected as the primary key in Table @tbl-table-primary-key-natural-key-example-person. 
If this key is entered incorrectly in the first entry, it will be necessary to change this information entered as Foreign Key in all tables connected to this key, for example (PERSON_TRAINING, PERSON_EXPERIENCE).



|    PERSON    |    |
|:------------:|:--:|
| TcIdentityNo | PK |
| FirstName    |    |
| LastName     |    |

: Natural Key Example 2 - Person Table {#tbl-table-primary-key-natural-key-example-person}

In table @tbl-table-primary-key-natural-key-example-address-table, a somewhat extreme example is the Address table. 
It is difficult to find a suitable natural key in the address table, so all the information entered had to be made as a composite key.



|     ADDRESS   |    |
|:-------------:|:--:|
| AddressLine1  | PK |
| AddressLine1  | PK |
| ApartmentName | PK |
| ApartmentNo   | PK |
| PostalCode    | PK |
| County        | PK |
| CityNo        | PK |
| CountryNo     | PK |

:  Natural Key Example 3 - Address Table {#tbl-table-primary-key-natural-key-example-address-table}





