## Vektor veri tabanları 

Üretken yapay zekanın (Generative AI) populer olması ile RAG (retrieval augmented generation) uygulamaları için vektpr veri tabanlarının populerliği artmıştır.
Aşağıda bir RAG uygulaması için nasıl çalıştıklarına dair bir örnek görülebilir.

{{< include ../course-contents/diagrams/how-vector-databases-works-tr.md >}}

Bu veri tabanlarında veriler bir vektor olarak tutulmakta ve vektor operasyonları daha hızlı olarak yapılmaktadır.
Bilinen veri tabanları  bu özellikleri sunmaya başlamıştır.

- postgres
- oracle
- MariaDb
- MongoDb
- Couchbase
- Neo4J
- Redis

Ama ayrıca sadece vektor veri tabanı olarak çalışan ürünlerde vardır.

- Pinecone
- Milvus
- Qdrant
- Chroma

Aşağıdaki yazı vector veritabanlarının yanlış soyutlama olduğunu iddia ediyor.
Vector veri tabanı kullanmak yerine, vector gömülü verilerinin (embeddings) indeks mantığında veri tabanı tarafından yönetilmesinin daha mantıklı olduğunu söylüyor.

[vector veritabanları yanlış soyutlamadır](https://www.timescale.com/blog/vector-databases-are-the-wrong-abstraction)

[SQL-Server vektor veri tipi](https://devblogs.microsoft.com/azure-sql/eap-for-vector-support-refresh-introducing-vector-type/)

[Oracle vektor veri tipi](https://docs.oracle.com/en/database/oracle/oracle-database/23/vecse/create-tables-using-vector-data-type.html)

[Sqlite vektor arama genişlemesi](https://github.com/asg017/sqlite-vec)
