# Open Source vs Commercial Databases

The big companies and government still heavily rely on commercial enterprise databases.

- Oracle
- SQL Server
- IBM DB2

But small to mid sized companies started to work with mostly open source databases in recent decade.
10 years ago, it was almost impossible to use open source databases in the large companies but mindset is shifted.
Even in large companies and government, you can find open source databases like postgre and mysql since small applications use them.

## Who use commercial databases

- Banks
- Government offices
- Large companies who need ERP suites


## Who uses open source databases

### sqlite

sqlite is the most used open source database. There are over [1 trillion (1e12) SQLite databases in active use](https://www.sqlite.org/mostdeployed.html).
sqlite is found on

- Every Android device
- Every iPhone and iOS device
- Every Mac
- Every Windows10 machine
- Every Firefox, Chrome, and Safari web browser 
...


### Mysql 

Wordpress uses mysql and and [472 million websites](https://colorlib.com/wp/wordpress-statistics/) runs on wordpress, which is 43.3% of all the websites on the internet.

### Postgres
- [Who uses postgres](https://dzone.com/articles/why-everyone-uses-postgres)
