# SQLite Sanal Tabloları (virtual tables)

- [sqlite dokümantasyonundan](https://www.sqlite.org/vtab.html)

>Sanal tablo, açık bir SQLite veritabanı bağlantısıyla kayıtlı bir nesnedir. 
> Bir SQL ifadesinin perspektifinden, sanal tablo nesnesi diğer herhangi bir tablo veya görünüm gibi görünür. 
> Ancak sahne arkasında, sanal tablodaki sorgular ve güncellemeler, veritabanı dosyasında okuma ve yazma yapmak yerine sanal tablo nesnesinin geri çağırma yöntemlerini çağırır.

Sqlite sanal tablolarının çok ilginç kullanım örnekleri var.

- [csv file](https://www.sqlite.org/csv.html)
- [zip file](https://www.sqlite.org/zipfile.html)


## CSV Sanal Tabloları örnek

1. csv extension'u yükleyin.

```sql
.load sqlite-extensions/csv.so 
```

2. Örnek csv dosyası oluştur.

```sql
.mode csv 
.headers on
.once deneme.csv 
SELECT FirstName,LastName FROM Customer; 
```

3. Sanal CSV tablosu oluştur.

```sql
CREATE VIRTUAL TABLE temp.t1 USING csv(filename='deneme.csv');
```

4. Sanal CSV tablosunu sorgula.

```sql
SELECT * FROM t1; 
```


## Zip Sanal Tabloları örnek

1. Örnek bir zip dosyası oluşturalım.

```bash
zip -r oracle-chinook.zip oracle-chinook/
```

2. sqlite3 açalım

3. 

```sql
SELECT name FROM zipfile('oracle-chinook.zip'); 
```

4. 

```sql
CREATE VIRTUAL TABLE temp.zip USING zipfile('oracle-chinook.zip');
```

5. normal bir dosya ekleme

```sql
INSERT INTO temp.zip(name, data) VALUES('a.txt', 'Atilla Özgür');   
```

 

[sqlite için diğer sanal tabloların belgelerine](https://www.sqlite.org/vtablist.html) bakın


