# SQL mathematical functions

Some common math functions are given below.

- ABS

	absolute value

- CEILING

	find nearest integer, larger than the input.
	Ceil goes up, floor goes down.

```sql
select ceiling(0.5); 
```


```sql
select ceiling(0.99),ceiling(0.1),ceiling(0.5);
```
> 1.0 | 1.0 | 1.0



- COS

cosine function

- DEGREES

	convert from radian to degrees

- EXP

	compute $e^x$ power

- FLOOR

find nearest integer, lesser than the input.
Ceil goes up, floor goes down.


```sql
select floor(0.99),floor(0.1),floor(0.5);
```

> 0.0 | 0.0 | 0.0


- LOG

	logarithmic function for given base

```sql
select log(2,32);  
```

> 5.0         

- LOG2

	logarithmic function for base 2

- LOG10

	logarithmic function for base 10

```sql
select log10(100);                                                                           
```

> 2.0         

- MOD

the remainder after dividing X by Y. This is similar to the '%' operator



- PI

constant PI value

- POWER

	compute $x^y$ power, like $2^3$ 


```sql
select power(2,3); 
```

- RADIANS

	Convert to radians from degrees



- SIGN

sign of n. That is

```math
if n<0 then -1

if n=0 then 0 

if n>0 then 1 
```



- SIN
sinus function

```sql
select sin(90); 
```

> 0.893996663600558


```sql
select sin(radians(90)); 
```

> 1.0

SQRT

square root



TAN

tangent function


## Math functions documentation

- [sqlite Built-In Mathematical SQL Functions](https://www.sqlite.org/lang_mathfunc.html)
- [sql server math function](https://learn.microsoft.com/en-us/sql/t-sql/functions/mathematical-functions-transact-sql?view=sql-server-ver16)
- [oracle numeric functions](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/Single-Row-Functions.html#GUID-AC0E8A99-5097-4147-8295-C88EAC5AA362)