# SQL Sanal Tablolar (virtual tables)

Sanal tablo jargonu, veritabanında verileri saklanmayan ancak sql ifadelerinizde tablo gibi davranan nesneler için kullanılır.

Görünümler (views) sanal tablolar için en bilinen örnektir.
CREATE VIEW ifadesini kullanarak görünümler oluşturuyoruz.

Normalde, görünüm verileri veritabanımızda saklanmaz.
Yalnızca görünüm sorgu tanımı veri sözlüğünde saklanır.
Bu konu hakkında daha fazla bilgi için ders notlarındaki görünümlere @sec-sql-views bakınız.

WITH ifadeleri de sanal tablolar gibi davranır.
Ayrıca FROM ifadelerinde tablo yerine alt sorgu kullanıldığında bu alt sorgular da sanal tablolar gibi davranır.

Bazı fonksiyonlar tablo benzeri veri döndürebilir.
Bu fonksiyon sonuçları sanal tablo veya satır içi görünümler olarak düşünülebilir.
sqlite'daki generate_series fonksiyonu iyi bir örnektir.


```sql
SELECT value FROM generate_series(5,100,5);
```

::: {.callout-warning}

Yukarıdaki sql, 3.34 sürümünden sonraki sql CLI'da çalışır, bkz. [release notes SQLite Release 3.34.0 On 2020-12-01](https://www.sqlite.org/releaselog/3_34_0.html)


Yukarıdaki sql, sqlite jdbc sürücüsünün sınırlamaları nedeniyle dbeaver'da **ÇALIŞMAYACAKTIR**, bakınız: [github xerial/sqlite-jdbc issue 1173](https://github.com/xerial/sqlite-jdbc/issues/1173).

Ocak 2025'te kontrol edilmiştir.
:::




Diğer bazı örneklere bakın

- [oracle json table](https://docs.oracle.com/en/database/oracle/oracle-database/23/adjsn/sql-json-function-json_table.html)



## Sqlite Sanal Tabloları (virtual tables)

- [sqlite dokümantasyonundan](https://www.sqlite.org/vtab.html)

>Sanal tablo, açık bir SQLite veritabanı bağlantısıyla kayıtlı bir nesnedir. 
> Bir SQL ifadesinin perspektifinden, sanal tablo nesnesi diğer herhangi bir tablo veya görünüm gibi görünür. 
> Ancak sahne arkasında, sanal tablodaki sorgular ve güncellemeler, veritabanı dosyasında okuma ve yazma yapmak yerine sanal tablo nesnesinin geri çağırma yöntemlerini çağırır.

Sqlite sanal tablolarının çok ilginç kullanım örnekleri var.

- [csv file](https://www.sqlite.org/csv.html)
- [zip file](https://www.sqlite.org/zipfile.html)

[sqlite için diğer sanal tabloların belgelerine](https://www.sqlite.org/vtablist.html) bakın

