# Veri Tanım Dili (DDL) SQLite



Sqlite aşağıdaki ortak veritabanı nesnelerine izin verir:

- Tablolar (Tables)
- Görünümler (Views)
- İndeksler (Indexes)
- Tetikleyici (Triggers)

Sqlite ayrıca [sanal tablolara](sql-virtual-tables-en.qmd) izin verir ancak bu sanal tablo sql server ve oracle versiyonlarından biraz farklıdır.

SQLite için:

- [Create Table](https://www.sqlite.org/lang_createtable.html)
- [Create Trigger](https://www.sqlite.org/lang_createtrigger.html)
- [Create Index](https://www.sqlite.org/lang_createindex.html)
- [Create View](https://www.sqlite.org/lang_createview.html)

Çoğu modern GUI aracı bu ifadeleri oluşturmanıza yardımcı olduğundan, bunların tam tanımlarını ezberlemenize gerek yoktur.

1. DBeaver Demo Create Table
2. DBeaver Demo Alter Table
3. DBeaver Demo Drop Table

1. DBeaver Demo Create View
2. DBeaver Demo Drop View


Açık kaynaklı ve ücretsiz bir araç olan DBeaver çok güçlü değildir.


Sqlite'ın KULLANICI (USER) nesnesine dosya tabanlı bir veritabanı olmasına ihtiyacı yoktur. 
Bu nedenle, kullanıcılar için güvenlik, roller ve ayrıcalıkları ele almak için çeşitli komutlara SQLite'ın ihtiyacı yoktur.

