# Why learn SQL Language?

## Reason 1: SQL is popular and widely used  {.unnumbered} 


SQL is the [number 8 in the tiobe index](https://www.tiobe.com/tiobe-index/sql/).
Note that, SQL is new in this list since it was not considered programming language before 2018.
But as [same web page](https://www.tiobe.com/tiobe-index/) says

> The programming language SQL was added to the TIOBE index in 2018 after somebody pointed out that SQL is Turing Complete. So although this language is very old, it has only a short history in the index.

[SQL Tetris in Postgresql for turing complete example](https://github.com/nuno-faria/tetris-sql)

{{< include ../course-contents/sql-in-career-sites-en.md >}}


## Reason 2: SQL is used in places other than databases  {.unnumbered} 

SQL widely used in data science with databases and in memory data frames.
Data frames are in memory tables. 
Both python and R has different data frame implementations.
You could use SQL to create data frames from databases and query data frames themselves.
See below:

- [Query python pandas data frame](https://stackoverflow.com/questions/45865608/executing-an-sql-query-on-a-pandas-dataset)

- [Query R Data frame](https://www.rdocumentation.org/packages/sqldf/versions/0.4-11)

SQL is also used for other use cases like querying logs.

- [Query logs using SQL via log parser](https://techcommunity.microsoft.com/t5/exchange-team-blog/introducing-log-parser-studio/ba-p/601131)

Also, querying csv and excel files using SQL is possible.

- [Query csv files using SQL](https://superuser.com/questions/7169/querying-a-csv-file)

- [Query excel files using SQL](https://stackoverflow.com/questions/18798522/how-to-run-a-sql-query-on-an-excel-table)


##  Reason 3: SQL is better compared to newer query languages  {.unnumbered} 

See below:

- [I don't need your query language](https://antonz.org/fancy-ql/)




