# SQL Working with NULL


- NULL is used for unknown or missing values.
- null means "unknown" so that any comparison or operation results in unknown. 
- for mathematical operations and logical operations, you may think null as $\infty$ in calculus.



- $\infty$ $!=$ $\infty$
- NULL $!=$ NULL
- 3 + NULL = NULL
- 'string value' + NULL = NULL

- for comparisons, null comparison always return false.

    * NULL = NULL returns false
    * NULL IS NULL returns true


sqlite
``` sql
select null = null;
```

``` sql
select null is null;
```

oracle

``` sql
SELECT  * FROM dual WHERE NULL = NULL;


SELECT  * FROM dual WHERE NULL IS NULL;
```
  


## NULL Working 1

{{< include ../course-contents/tables/table-null-3-valued-logic.md >}}

{{< include ../course-contents/tables/table-null-not-operation.md >}}


{{< include ../course-contents/sql-null-functison-sql-standard-en.qmd >}}




### NULL Functions SQL Server



- ISNULL(kolon/degisken,**deger**)
- Eğer kolon/degişken null ise **degeri** döndürür.

- NULLIF(kolon/degisken,**deger**)
- Eğer kolon/degişken **deger**'e eşitse NULL döndürür.
- COALESCE(kolon/degisken1,kolon/degisken2,..)
- kolon/degişken listesi içindeki ilk NULL olmayan değeri döndürür.


SQL NULL Functions

    IFNULL(), ISNULL(), COALESCE(), and NVL() Functions
    

### NULL ile çalışma - COALESCE Örnek


``` sql
    SELECT 
    COALESCE(ADI + ' ' + IKINCIADI + ' ' + SOYADI
    ,ADI + ' ' + SOYADI
     ) AS TAMADI FROM ORTAK.KISI;
```









