# SQL Stored Procedures {#sec-sql-stored-procedures}

There are no stored procedures in sqlite but both oracle and sql server have them.
Normally, stored procedures and functions are written using the sql dialects. 
For Oracle PL/SQL and for Sql Server T-SQL.

But these two databases and sqlite also allows using other languages for writing functions or stored procedures.

- Sqlite allows writing C language functions.
- SQL Server allows .NET languages (for example: C#) for stored procedures
- Oracle allows [java](https://docs.oracle.com/en/database/oracle/oracle-database/19/jjdev/invoking-Java-methods.html), [.NET](https://www.oracle.com/webfolder/technetwork/tutorials/obe/db/10g/r2/prod/install/odpinst/odpinst_otn.htm), [javascript](https://docs.oracle.com/en/database/oracle/oracle-database/23/mlejs/introduction-to-mle.html#GUID-EDC075CA-B50E-45D8-8A72-D060C6DB47DB), and programming languages for stored procedures.



A stored procedure is a group of SQL statements in data dictionary.
These SQL statements are mostly dialects of given database, PL-SQL and T-SQL.
You could call these procedures using their name.


I personally do not like to use stored procedures much since they are hard to control using standard version control (git) systems.
Most of the time, writing necessary code in given backend code is a better choice.
But database vendors provide a lot of ready to use stored procedures.
Instead of writing custom code, using these ready stored procedures or functions is a always better.



{{< include ../course-contents/sql-stored-procedures-oracle-en.qmd >}}
{{< include ../course-contents/sql-stored-procedures-sqlserver-en.qmd >}}
