project:
  type: book
  execute-dir: "project"
  
book:
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  output-file: "databases"


profile:
  default: en
  group: 
    - [en,tr]



format:
  html:
    theme: cosmo
    mermaid:
      theme: forest
  pdf:
    documentclass: scrreprt
    latex-output-dir: _output
    mermaid:
      theme: forest


