project:
  type: book
  execute-dir: "project"
  output-dir: ./_site

book:
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  output-file: "databases"
  title: "Introduction to databases (Veri tabanlarına giriş)"
  chapters:
      - index.qmd


profile:
  default: def
  group: 
    - [def,en,tr]



format:
  html:
    theme: cosmo
    mermaid:
      theme: forest
  pdf:
    documentclass: scrreprt
    latex-output-dir: _output
    mermaid:
      theme: forest
