project:
  output-dir: ./_site/en

book:
  title: "Introduction to databases"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html  
  chapters:
    - index.qmd
    - part: "Course Introduction"
      chapters:
        - Syllabus-en.qmd
        - course-contents/course-introduction-en.qmd
    - part: "Database Introduction"
      chapters:        
        - course-contents/databases-intro-en.qmd
        - course-contents/database-convergence-en.md
        - course-contents/database-types-en.qmd
        - course-contents/database-ranking-market-share-en.qmd
        - course-contents/open-source-vs-enterprise-databases-en.qmd
        - course-contents/which-databases-will-be-covered-en.md 
        - course-contents/database-playground-en.md
        - course-contents/server-installation-en.qmd
        - course-contents/database-connections-en.qmd
        - course-contents/example-database-schemas-en.qmd
        - course-contents/command-line-access-en.qmd
        - course-contents/sql-clients-GUI-en.qmd
    - part: "Database Design Intro"
      chapters:
        - course-contents/er-model-en.qmd
        - course-contents/er-model-mermaid-diagrams-en.qmd
    - part: "SQL Intro"
      chapters:
        - course-contents/sql-why-learn-en.qmd
        - course-contents/sql-history-en.qmd
        - course-contents/sql-introduction-en.qmd
        - course-contents/sql-standard-en.qmd
        - course-contents/sql-dialects-en.qmd
        - course-contents/sql-command-types-en.qmd
    - part: "SQL DQL"
      chapters:
        - course-contents/sql-DQL-data-query-language-en.md
        - course-contents/sql-select-en.qmd
        - course-contents/sql-comments-en.qmd
        - course-contents/sql-select-distinct-en.md
        - course-contents/sql-where-en.qmd
        - course-contents/sql-null-en.qmd
        - course-contents/sql-null-functions-en.qmd
        - course-contents/sql-aggregate-functions-en.qmd
        - course-contents/sql-group-by-en.qmd
        - course-contents/sql-orderby-en.qmd
        - course-contents/sql-limit-top-en.md
        - course-contents/sql-set-en.qmd
        - course-contents/sql-join-en.qmd
        - course-contents/sql-subqueries-en.qmd
        - course-contents/sql-with-en.qmd
        - course-contents/sql-paging-en.qmd
        - course-contents/sql-views-en.qmd
        - course-contents/sql-virtual-tables-en.qmd
        - course-contents/sql-deterministic-functions-en.qmd
        - course-contents/sql-string-functions-en.qmd
        - course-contents/sql-mathematical-functions-en.qmd
        - course-contents/sql-scalar-functions-en.qmd
        - course-contents/sql-json-functions-en.qmd
        - course-contents/sql-functions-other-en.qmd 
       
    - part: "SQL DML-DCL-TCL"
      chapters:
        - course-contents/sql-DML-data-manipulation-language-en.qmd
        - course-contents/sql-truncate-table-en.md
        - course-contents/sql-DDL-data-definition-language-en.qmd
        - course-contents/sql-DCL-data-control-language-en.qmd
        - course-contents/sql-TCL-transactional-control-language-en.qmd
    - part: "Database Design Advanced"
      chapters:
        - course-contents/database-design-en.qmd
        - course-contents/database-desing-patterns-en.qmd
        - course-contents/sql-data-types-en.qmd
        - course-contents/sql-constraints-en.qmd
        - course-contents/sql-indexes-intro-en.qmd
    - course-contents/suggested-readings-en.md
    - course-contents/suggested-books-en.md
    - summary-en.qmd
    - references-en.qmd
