project:
  output-dir: ./_site/tr
book:
  title: "Veritabanlarına Giriş"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html

  chapters:
    - part: "Kursa Giriş"
      chapters:
        - index.qmd
        - Syllabus-tr.qmd
        - course-contents/course-introduction-tr.qmd
    - part: "Veritabanlarına Giriş"
      chapters:
        - course-contents/databases-intro-tr.qmd
        - course-contents/database-types-tr.qmd
        - course-contents/database-ranking-market-share-tr.qmd
        - course-contents/open-source-vs-enterprise-databases-tr.qmd
        - course-contents/which-databases-will-be-covered-tr.md 
        - course-contents/database-playground-tr.md

        - course-contents/server-installation-tr.qmd
        - course-contents/database-connections-tr.qmd
        - course-contents/example-database-schemas-tr.qmd
        - course-contents/command-line-access-tr.qmd
        - course-contents/sql-clients-GUI-tr.qmd

    - part: "SQL"
      chapters:
        - course-contents/sql-introduction-en.qmd
        - course-contents/sql-DQL-data-query-language-en.md
        - course-contents/sql-select-en.qmd
        - course-contents/sql-data-types-en.qmd
        - course-contents/sql-select-distinct-en.md
        - course-contents/sql-where-en.qmd
        - course-contents/sql-null-en.qmd
        - course-contents/sql-aggregate-functions-en.qmd
        - course-contents/sql-orderby-en.qmd
        - course-contents/sql-limit-top-en.md
        - course-contents/sql-paging-en.qmd
        - course-contents/sql-set-en.qmd
        - course-contents/sql-join-en.qmd
        - course-contents/sql-DML-data-manipulation-language-en.qmd
        - course-contents/sql-truncate-table-en.md
        - course-contents/sql-DDL-data-definition-language-en.qmd
        - course-contents/sql-DCL-data-control-language-en.qmd
        - course-contents/sql-TCL-transactional-control-language-en.qmd

    - course-contents/suggested-readings-en.md
    - course-contents/suggested-books-en.md
    - summary.qmd
    - references.qmd





