project:
  type: book

book:
  title: "Veritabanlarına Giriş"

  chapters:
    - part: "Course Introduction"
      chapters:
        - index.qmd
        - Syllabus-tr.qmd
        - course-contents/course-introduction-tr.qmd
    - part: "Database Introduction"
      chapters:        
        - course-contents/databases-intro-tr.qmd
        - course-contents/database-ranking-market-share-tr.qmd
        - course-contents/open-source-vs-enterprise-databases-tr.qmd
        - course-contents/which-databases-will-be-covered-tr.md 
        - course-contents/database-playground-en.md
        - course-contents/database-connections-en.qmd
        - course-contents/example-database-schemas-en.qmd
        - course-contents/server-installation-en.qmd
        - course-contents/command-line-access-en.qmd
        - course-contents/sql-clients-GUI-en.qmd

    - part: "SQL"
      chapters:
        - course-contents/sql-introduction-en.qmd
        - course-contents/sql-DQL-data-query-language-en.md
        - course-contents/sql-select-en.qmd
        - course-contents/sql-data-types-en.qmd
        - course-contents/sql-select-distinct-en.md
        - course-contents/sql-where-en.qmd
        - course-contents/sql-null-en.qmd
        - course-contents/sql-aggregate-functions-en.qmd
        - course-contents/sql-orderby-en.qmd
        - course-contents/sql-limit-top-en.md
        - course-contents/sql-paging-en.qmd
        - course-contents/sql-set-en.qmd
        - course-contents/sql-join-en.qmd
        - course-contents/sql-DML-data-manipulation-language-en.qmd
        - course-contents/sql-truncate-table-en.md
        - course-contents/sql-DDL-data-definition-language-en.qmd
        - course-contents/sql-DCL-data-control-language-en.qmd
        - course-contents/sql-TCL-transactional-control-language-en.qmd

    - course-contents/suggested-readings-en.md
    - course-contents/suggested-books-en.md
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



