project:
  type: book

book:
  title: "Introduction to databases"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
        - Syllabus.qmd        
        - course-contents/course-introduction-en.qmd
        - course-contents/databases-intro-en.qmd
    - part: "SQL"
      chapters:
        - course-contents/sql-introduction-en.qmd
        - course-contents/sql-select-en.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



