project:
  type: book

book:
  title: "Introduction to databases"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
        - Syllabus-en.qmd
        - course-contents/course-introduction-en.qmd
        - course-contents/databases-intro-en.qmd
        - course-contents/open-source-vs-enterprise-databases-en.qmd
        - course-contents/example-database-schemas-en.qmd
        - course-contents/server-installation-en.qmd
        - course-contents/sql-clients-GUI-en.qmd

    - part: "SQL"
      chapters:
        - course-contents/sql-introduction-en.qmd
        - course-contents/sql-DQL-data-query-language-en.md
        - course-contents/sql-select-en.qmd
        - course-contents/sql-data-types-en.qmd
        - course-contents/sql-select-distinct-en.md
        - course-contents/sql-where-en.qmd
        - course-contents/sql-null-en.qmd
        - course-contents/sql-aggregate-functions-en.qmd
        - course-contents/sql-orderby-en.qmd
        - course-contents/sql-limit-top-en.md
        - course-contents/sql-paging-en.qmd
        - course-contents/sql-set-en.qmd
        - course-contents/sql-join-en.qmd
        - course-contents/sql-DML-data-manipulation-language-en.qmd
        - course-contents/sql-truncate-table-en.md
        - course-contents/sql-DDL-data-definition-language-en.qmd
        - course-contents/sql-DCL-data-control-language-en.qmd
        - course-contents/sql-TCL-transactional-control-language-en.qmd

    - course-contents/suggested-readings-en.md
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



