project:
  output-dir: ./_site/tr
book:
  title: "Veritabanlarına Giriş"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html

  chapters:
    - part: "Kursa Giriş"
      chapters:
        - index.qmd
        - Syllabus-tr.qmd
        - course-contents/course-introduction-tr.qmd
    - part: "Veritabanlarına Giriş"
      chapters:
        - course-contents/databases-intro-tr.qmd
        - course-contents/database-models-tr.qmd

        - course-contents/database-ranking-market-share-tr.qmd
        - course-contents/open-source-vs-commercial-databases-tr.qmd
        - course-contents/database-types-tr.qmd
        
        - course-contents/database-convergence-tr.md
        - course-contents/which-databases-will-be-covered-tr.md 
        - course-contents/why-start-with-sqlite-tr.qmd 
        - course-contents/database-playground-tr.md
        - course-contents/server-installation-sqlite-tr.qmd
        - course-contents/server-installation-oracle-tr.qmd
        - course-contents/server-installation-sqlserver-tr.qmd
        - course-contents/example-database-schemas-tr.qmd
        - course-contents/command-line-access-tr.qmd
        - course-contents/command-line-sqlite-intro-tr.qmd
        - course-contents/command-line-sqlite-reference-tr.qmd
        - course-contents/sql-clients-GUI-generic-tr.qmd
        - course-contents/sql-clients-GUI-sqlite-tr.qmd
        - course-contents/sql-clients-GUI-oracle-tr.qmd
        - course-contents/sql-clients-GUI-sqlserver-tr.qmd
        - course-contents/database-connections-tr.qmd

    - part: "Veritabanı Tasarım Giriş"
      chapters:
        - course-contents/er-model-tr.qmd
        - course-contents/er-model-mermaid-diagrams-tr.qmd


    - part: "SQL Giriş"
      chapters:
        - course-contents/sql-why-learn-tr.qmd
        - course-contents/sql-history-tr.qmd
        - course-contents/sql-introduction-tr.qmd
        - course-contents/sql-dialects-tr.qmd
        - course-contents/sql-command-types-tr.qmd

    - part: "DDL (Veri Tanım Dili) Giriş"
      chapters:
        - course-contents/sql-DDL-data-definition-language-tr.qmd
        - course-contents/sql-DDL-data-definition-language-sqlite-tr.qmd
        - course-contents/sql-data-dictionary-tr.qmd
        - course-contents/sql-data-dictionary-sqlite-tr.qmd

    - part: "SQL DQL (Select)"
      chapters:
        - course-contents/sql-select-tr.qmd
        - course-contents/database-schema-object-names-tr.qmd
        - course-contents/sql-alias-tr.qmd
        - course-contents/sql-case-sensitivity-tr.qmd
        - course-contents/sql-string-concat-tr.qmd
        - course-contents/sql-comments-tr.qmd
        - course-contents/sql-select-distinct-tr.md
        - course-contents/sql-where-tr.qmd
        - course-contents/sql-where-glob-tr.qmd


        - course-contents/sql-null-tr.qmd
        - course-contents/sql-functions-null-sql-standard-tr.qmd
        - course-contents/sql-functions-null-sqlite-tr.qmd
        - course-contents/sql-functions-null-sql-server-tr.qmd
        - course-contents/sql-functions-null-oracle-tr.qmd

        - course-contents/sql-functions-aggregate-tr.qmd
        - course-contents/sql-functions-aggregate-sqlite-tr.qmd
        - course-contents/sql-group-by-tr.qmd
        - course-contents/sql-orderby-tr.qmd
        - course-contents/sql-limit-top-tr.md
        - course-contents/sql-set-tr.qmd
        - course-contents/sql-join-tr.qmd
        - course-contents/sql-subqueries-tr.qmd
        - course-contents/sql-with-tr.qmd
        - course-contents/sql-paging-tr.qmd
        - course-contents/sql-views-tr.qmd
        - course-contents/sql-virtual-tables-tr.qmd

    - part: "SQL: Functions, Stored Procedures, Triggers, Extensions"
      chapters:
        - course-contents/sql-functions-scalar-en.qmd
        - course-contents/sql-functions-string-en.qmd
        - course-contents/sql-functions-mathematical-en.qmd
        - course-contents/sql-functions-date-and-time-en.qmd
        - course-contents/sql-functions-json-en.qmd
        - course-contents/sql-stored-procedures-en.qmd
        - course-contents/sql-triggers-en.qmd
        - course-contents/sql-sqlite-extensions-tr.qmd
    - part: "SQL: İleri Seviye"
      chapters:
        - course-contents/sql-functions-window-en.qmd
    - part: "SQL DML-DCL-TCL"
      chapters:
        - course-contents/sql-DML-data-manipulation-language-tr.qmd
        - course-contents/sql-DML-insert-en.qmd
        - course-contents/sql-DML-update-en.qmd
        - course-contents/sql-DML-delete-en.qmd
        - course-contents/sql-DCL-data-control-language-tr.qmd
        - course-contents/sql-TCL-transactional-control-language-tr.qmd
    - part: "Veri tabanı Kavramları"
      chapters:
        - course-contents/database-concepts-ACID-en.qmd
        - course-contents/database-concepts-isolation-en.qmd
        - course-contents/database-concepts-pages.qmd
        - course-contents/database-concepts-sqlite-journal-modes-en.qmd
        - course-contents/database-concepts-import-export-en.qmd
        - course-contents/database-concepts-backup-restore-en.qmd

    - part: "Veritabanı Tasarımı İleri"
      chapters:
        - course-contents/database-design-tr.qmd
        - course-contents/database-design-primary-key-tr.qmd
        - course-contents/database-design-primary-key-uuid-guid-en.qmd
        - course-contents/database-desing-patterns-en.qmd
        
        - course-contents/sql-data-types-tr.qmd
        - course-contents/sql-data-types-string-tr.qmd
        - course-contents/sql-data-types-string-collation-tr.qmd
        - course-contents/sql-data-types-float-tr.qmd
        - course-contents/sql-data-types-sqlite-tr.qmd
        - course-contents/sql-data-types-sqlserver-tr.qmd


        - course-contents/sql-constraints-en.qmd
        - course-contents/database-design-from-user-interfaces-tr.qmd
        - course-contents/database-design-from-spreadsheets-en.qmd
        - course-contents/database-design-questions-answers-en.qmd
        - course-contents/database-design-normal-forms.qmd

    - part: "DDL (Veri Tanım Dili) İleri"
      chapters:
        - course-contents/sql-DDL-data-definition-language-advanced-tr.qmd
        - course-contents/sql-DML-alter-table-tr.qmd
        - course-contents/sql-truncate-table-tr.md


    - part: "SQL Tuning"
      chapters:
        - course-contents/sql-indexes-intro-en.qmd

    - course-contents/suggested-readings-tr.md
    - course-contents/suggested-books-tr.md
    - summary-tr.qmd
    - references-tr.qmd





