project:
  type: book

book:
  title: "Introduction to databases"
  author: "Atilla Özgür"
  date: today
  date-format: "YYYY-MM-DD"
  cover-image: cover.png
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - intro.qmd
        - Syllabus.qmd        
        - course-contents/course-introduction-en.qmd
        - course-contents/databases-intro-en.qmd
        - course-contents/example-database-schemas-en.qmd
    - part: "SQL"
      chapters:
        - course-contents/sql-introduction-en.qmd
        - course-contents/sql-select-en.qmd
        - course-contents/sql-data-types-en.qmd
        - course-contents/sql-select-distinct-en.md
        - course-contents/sql-where-en.qmd
        - course-contents/sql-null-en.qmd
        - course-contents/sql-orderby-en.qmd
        - course-contents/sql-limit-top-en.md
        - course-contents/sql-paging-en.qmd
    - course-contents/suggested-readings-en.md
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



