project:
  output-dir: ./_site/tr
book:
  title: "Veritabanlarına Giriş"
  navbar:
    background: primary
    search: true
    right:
      - text: "English"
        href: ../en/index.html
      - text: "Türkçe"
        href: ../tr/index.html

  chapters:
    - part: "Kursa Giriş"
      chapters:
        - index.qmd
        - Syllabus-tr.qmd
        - course-contents/course-introduction-tr.qmd
    - part: "Veritabanlarına Giriş"
      chapters:
        - course-contents/databases-intro-tr.qmd
        - course-contents/database-models-tr.qmd

        - course-contents/database-ranking-market-share-tr.qmd
        - course-contents/open-source-vs-commercial-databases-tr.qmd
        - course-contents/database-types-tr.qmd
        
        - course-contents/which-databases-will-be-covered-tr.md 
        
        - course-contents/server-installation-tr.qmd
        - course-contents/database-playground-tr.md
        - course-contents/database-connections-tr.qmd
        - course-contents/example-database-schemas-tr.qmd
        - course-contents/command-line-access-tr.qmd
        - course-contents/sql-clients-GUI-tr.qmd

    - part: "SQL Giriş"
      chapters:
        - course-contents/sql-introduction-tr.qmd
        - course-contents/sql-standard-tr.qmd
        - course-contents/sql-dialects-tr.qmd
        - course-contents/sql-command-types-tr.qmd
    - part: "SQL DQL"
      chapters:
        - course-contents/sql-DQL-data-query-language-tr.md
        - course-contents/sql-select-tr.qmd
        - course-contents/sql-comments-tr.qmd
        - course-contents/sql-select-distinct-tr.md
        - course-contents/sql-where-tr.qmd
        - course-contents/sql-null-tr.qmd
        - course-contents/sql-functions-aggregate-tr.qmd
        - course-contents/sql-group-by-tr.qmd
        - course-contents/sql-orderby-tr.qmd
        - course-contents/sql-limit-top-tr.md
        - course-contents/sql-paging-tr.qmd
        - course-contents/sql-set-tr.qmd
        - course-contents/sql-join-tr.qmd
    - part: "SQL DML-DCL-TCL"
      chapters:
        - course-contents/sql-DML-data-manipulation-language-tr.qmd
        - course-contents/sql-truncate-table-tr.md
        - course-contents/sql-DDL-data-definition-language-tr.qmd
        - course-contents/sql-DCL-data-control-language-tr.qmd
        - course-contents/sql-TCL-transactional-control-language-tr.qmd
    - part: "Veritabanı Tasarımı"
      chapters:
        - course-contents/database-design-tr.qmd
        - course-contents/sql-data-types-tr.qmd
        - course-contents/database-design-primary-key-tr.qmd
        - course-contents/database-design-primary-key-uuid-guid-en.qmd
        - course-contents/database-desing-patterns-en.qmd
        - course-contents/sql-constraints-en.qmd
        - course-contents/database-design-from-user-interfaces-tr.qmd
        - course-contents/database-design-from-spreadsheets-en.qmd
        - course-contents/database-design-questions-answers-en.qmd
        - course-contents/database-design-normal-forms.qmd

    - course-contents/suggested-readings-tr.md
    - course-contents/suggested-books-tr.md
    - summary-tr.qmd
    - references-tr.qmd





