name: quarto Render to pdf

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  create-pdf:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
      # Show render to html works

      - name: Render Quarto Project Profile en html
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: en
        with:
          to: html
      # Show render to pdf DOES NOT work
      - name: Render Quarto Project Profile en pdf
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: en
        with:
          to: pdf
